# This is a basic workflow to help you get started with Actions

name: ci-cd-for-app

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out source code
        uses: actions/checkout@v2

      # Generate major, minor tag
      - name: Get major and minor versions
        id: commit-tag
        run: |
          echo "MINOR_VERSION_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "MAJOR_VERSION_TAG=$(cat version)" >> $GITHUB_ENV

      # Generate tag (must be done on a separate step, otherwise it fails)
      - name: Generate tag
        run: |
          echo "VERSION_TAG=${{env.MAJOR_VERSION_TAG}}.${{env.MINOR_VERSION_TAG}}" >> $GITHUB_ENV

      - name: Use tag
        run: |
          echo "Current version is: ${{env.VERSION_TAG}}"
